### ISSUE TITLE
New Version of this script...

### ISSUE THREAD

**Issue by acasilla** [skaggej/powershell#1]
I would ask where you got this but I think I know.. we have a new version of this script if you are interested

**Comment by skaggej** [comment]
What script are you talking about?

**Comment by acasilla** [comment]
The getsearchinfo script

**Comment by skaggej** [comment]
Ah, ok. I honestly don't remember where I pulled it from, but found it useful and wanted to keep a copy of it. I'm guessing it wasn't already in GitHub because I would have just forked the source.
